=== FeatheredElephant/SolvdLaba/CarDealership/src/main/resources/carDealership.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="carDealership">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="users">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="user" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="userId"/>
                    <xs:element type="xs:string" name="name"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="payments">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="payment" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="paymentId"/>
                    <xs:element type="xs:float" name="amount"/>
                    <xs:element type="xs:int" name="userId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="employees">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="employee" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="employeeId"/>
                    <xs:element type="xs:float" name="wage"/>
                    <xs:element type="xs:string" name="title"/>
                    <xs:element type="xs:int" name="userId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="customers">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="customer" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="customerId"/>
                    <xs:element type="xs:int" name="userId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vehicleSales">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vehicleSale" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="saleId"/>
                    <xs:element type="xs:int" name="customerId"/>
                    <xs:element type="xs:int" name="vehicleId"/>
                    <xs:element type="xs:string" name="discount"/>
                    <xs:element type="xs:float" name="total"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="serviceProviders">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="serviceProvider" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="serviceProviderId"/>
                    <xs:element type="xs:string" name="userId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vehicleServices">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vehicleService" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="serviceId"/>
                    <xs:element type="xs:string" name="serviceProviderId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vendors">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vendor" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="vendorId"/>
                    <xs:element type="xs:int" name="userId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vehiclePurchases">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vehiclePurchase" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="purchaseId"/>
                    <xs:element type="xs:int" name="vehicleId"/>
                    <xs:element type="xs:int" name="vendorId"/>
                    <xs:element type="xs:float" name="cost"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vehiclePartPurchases">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vehcilePartPurchase" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="vehiclePartPurchaseId"/>
                    <xs:element type="xs:int" name="vendorId"/>
                    <xs:element type="xs:int" name="partId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vehicleParts">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vehiclePart" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="partId"/>
                    <xs:element type="xs:int" name="partTypeId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="partTypes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="partType" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="partTypeId"/>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:float" name="price"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vehicles">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vehicle" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="vehicleId"/>
                    <xs:element type="xs:short" name="year"/>
                    <xs:element type="xs:int" name="modelId"/>
                    <xs:element type="xs:int" name="colorId"/>
                    <xs:element type="xs:float" name="price"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="colors">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="color" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="colorId"/>
                    <xs:element type="xs:string" name="name"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="models">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="model" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="modelId"/>
                    <xs:element type="xs:string" name="name"/>
                    <xs:element type="xs:string" name="brand"/>
                    <xs:element type="xs:int" name="vehicletypeId"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="vehicleTypes">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="vehicleType" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="typeId"/>
                    <xs:element type="xs:string" name="name"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
        <xs:element name="brands">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="brand" maxOccurs="unbounded" minOccurs="0">
                <xs:complexType>
                  <xs:sequence>
                    <xs:element type="xs:int" name="brandId"/>
                    <xs:element type="xs:string" name="name"/>
                  </xs:sequence>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== FeatheredElephant/SolvdLaba/CarDealership/src/main/resources/carDealership.xml
<?xml version="1.0" encoding="UTF-8"?>

<carDealership noNamespaceSchemaLocation="carDealership.xsd">
	<users>
		<user>
			<userId>0</userId>
			<name>John</name>
		</user>
		<user>
			<userId>1</userId>
			<name>Jane</name>
		</user>
	</users>
	<payments>
		<payment>
			<paymentId>0</paymentId>
			<amount>-15.00</amount>
			<userId>0</userId>
		</payment>
		<payment>
			<paymentId>0</paymentId>
			<amount>-15.00</amount>
			<userId>0</userId>
		</payment>
	</payments>
	
	<employees>
		<employee>
			<employeeId>0</employeeId>
			<wage>15.00</wage>
			<title>Janitor</title>
			<userId>0</userId>
		</employee>
		<employee>
			<employeeId>0</employeeId>
			<wage>15.00</wage>
			<title>Janitor</title>
			<userId>0</userId>
		</employee>
	</employees>
	
	<customers>
		<customer>
			<customerId>0</customerId>
			<userId>0</userId>
		</customer>
		<customer>
			<customerId>0</customerId>
			<userId>0</userId>
		</customer>
	</customers>
	<vehicleSales>
		<vehicleSale>
			<saleId>0</saleId>
			<customerId>0</customerId>
			<vehicleId>0</vehicleId>
			<discount>10%</discount>
			<total>500.00</total>
		</vehicleSale>
		<vehicleSale>
			<saleId>0</saleId>
			<customerId>0</customerId>
			<vehicleId>0</vehicleId>
			<discount>10%</discount>
			<total>500.00</total>
		</vehicleSale>
	</vehicleSales>

	<serviceProviders>
		<serviceProvider>
			<serviceProviderId>0</serviceProviderId>
			<userId></userId>
		</serviceProvider>
		<serviceProvider>
			<serviceProviderId>0</serviceProviderId>
			<userId></userId>
		</serviceProvider>
	</serviceProviders>
	<vehicleServices>
		<vehicleService>
			<serviceId>0</serviceId>
			<serviceProviderId></serviceProviderId>
		</vehicleService>
		<vehicleService>
			<serviceId>0</serviceId>
			<serviceProviderId></serviceProviderId>
		</vehicleService>
	</vehicleServices>
	
	<vendors>
		<vendor>
			<vendorId>0</vendorId>
			<userId>0</userId>
		</vendor>
		<vendor>
			<vendorId>0</vendorId>
			<userId>0</userId>
		</vendor>
	</vendors>
	<vehiclePurchases>
		<vehiclePurchase>
			<purchaseId>0</purchaseId>
			<vehicleId>0</vehicleId>
			<vendorId>0</vendorId>
			<cost>100.00</cost>
		</vehiclePurchase>
		<vehiclePurchase>
			<purchaseId>0</purchaseId>
			<vehicleId>0</vehicleId>
			<vendorId>0</vendorId>
			<cost>100.00</cost>
		</vehiclePurchase>
	</vehiclePurchases>
	<vehiclePartPurchases>
		<vehcilePartPurchase>
			<vehiclePartPurchaseId>0</vehiclePartPurchaseId>
			<vendorId>0</vendorId>
			<partId>0</partId>
		</vehcilePartPurchase>
		<vehcilePartPurchase>
			<vehiclePartPurchaseId>0</vehiclePartPurchaseId>
			<vendorId>0</vendorId>
			<partId>0</partId>
		</vehcilePartPurchase>
	</vehiclePartPurchases>
	<vehicleParts>
		<vehiclePart>
			<partId>0</partId>
			<partTypeId>0</partTypeId>
		</vehiclePart>
		<vehiclePart>
			<partId>0</partId>
			<partTypeId>0</partTypeId>
		</vehiclePart>
	</vehicleParts>
	<partTypes>
		<partType>
			<partTypeId>0</partTypeId>
			<name>Engine</name>
			<price>100.00</price>
		</partType>
		<partType>
			<partTypeId>0</partTypeId>
			<name>Engine</name>
			<price>100.00</price>
		</partType>
	</partTypes>
	
	<vehicles>
		<vehicle>
			<vehicleId>0</vehicleId>
			<year>2000</year>
			<modelId>0</modelId>
			<colorId>0</colorId>
			<price>100.00</price>
		</vehicle>
		<vehicle>
			<vehicleId>0</vehicleId>
			<year>2000</year>
			<modelId>0</modelId>
			<colorId>0</colorId>
			<price>100.00</price>
		</vehicle>
	</vehicles>
	<colors>
		<color>
			<colorId>0</colorId>
			<name>Blue</name>
		</color>
		<color>
			<colorId>0</colorId>
			<name>Blue</name>
		</color>
	</colors>
	<models>
		<model>
			<modelId>0</modelId>
			<name>Fiesta</name>
			<brand>Ford</brand>
			<vehicletypeId>0</vehicletypeId>
		</model>
		<model>
			<modelId>0</modelId>
			<name>Fiesta</name>
			<brand>Ford</brand>
			<vehicletypeId>0</vehicletypeId>
		</model>
	</models>
	<vehicleTypes>
		<vehicleType>
			<typeId>0</typeId>
			<name>Sedan</name>
		</vehicleType>
		<vehicleType>
			<typeId>0</typeId>
			<name>Sedan</name>
		</vehicleType>
	</vehicleTypes>
	<brands>
		<brand>
			<brandId>0</brandId>
			<name>Ford</name>
		</brand>
		<brand>
			<brandId>0</brandId>
			<name>Ford</name>
		</brand>
	</brands>
</carDealership>
